import { useState } from 'react';
import { ShieldAlert, Cpu } from 'lucide-react';

const Header = () => {
  const [showModal, setShowModal] = useState(false);

  return (
    <header className="header-glass">
      <div className="header-brand">
        <div className="brand-icon">
          <Cpu className="icon-glow" size={28} />
        </div>
        <div>
          <h1 className="brand-title">Multi-Asset Price Predictor</h1>
          <p className="brand-subtitle">
            Real-Time Machine Learning Suite • Reliance, Bitcoin & Google
          </p>
        </div>
      </div>

      <div className="header-actions">
        <div className="live-status">
          <span className="pulse-dot"></span>
          <span className="live-text">API Online</span>
        </div>

        <button
          className="disclaimer-btn"
          onClick={() => setShowModal(true)}
          title="View Financial Disclaimer"
        >
          <ShieldAlert size={16} />
          <span>Disclaimer</span>
        </button>
      </div>

      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal-content glass-card" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <ShieldAlert className="warning-icon" size={24} />
              <h3>Financial Disclaimer</h3>
            </div>
            <div className="modal-body">
              <p>
                Predictions generated by this application are produced by machine learning models trained on historical time-series market data.
              </p>
              <p>
                <strong>They are statistical estimations for educational and technical analysis purposes only and DO NOT constitute guaranteed future prices or financial advice.</strong>
              </p>
              <p>
                Financial markets involve substantial risk. Always perform independent research before making investment decisions.
              </p>
            </div>
            <button className="primary-btn full-width" onClick={() => setShowModal(false)}>
              I Understand
            </button>
          </div>
        </div>
      )}
    </header>
  );
};

export default Header;
