import React, { useState } from 'react';
import { useRouter, Link } from '../router/RouterContext';
import { ShieldAlert, Cpu, ChevronDown, CheckCircle2 } from 'lucide-react';

const Navbar = ({ assets = [], selectedAssetId, onSelectAsset }) => {
  const { currentPath } = useRouter();
  const [showModal, setShowModal] = useState(false);
  const [showDropdown, setShowDropdown] = useState(false);

  const selectedAsset = assets.find((a) => a.id === selectedAssetId) || assets[0];

  return (
    <header className="navbar-header">
      <div className="navbar-container">
        {/* Brand */}
        <Link to="/" className="navbar-brand">
          <div className="brand-logo-icon">
            <Cpu size={22} className="brand-cpu" />
          </div>
          <div className="brand-text-group">
            <span className="brand-name">QuantAI Predictor</span>
            <span className="brand-tagline">Machine Learning Platform</span>
          </div>
        </Link>

        {/* Navigation Links */}
        <nav className="navbar-links">
          <Link to="/" className={`nav-link ${currentPath === '/' ? 'active' : ''}`}>
            Home
          </Link>
          <Link to="/models" className={`nav-link ${currentPath.startsWith('/models') ? 'active' : ''}`}>
            Models
          </Link>
          <Link to="/about" className={`nav-link ${currentPath === '/about' ? 'active' : ''}`}>
            About
          </Link>
        </nav>

        {/* Right Action Bar */}
        <div className="navbar-actions">
          {/* Asset Selector */}
          {assets.length > 0 && (
            <div className="asset-selector-wrapper">
              <button
                type="button"
                className="asset-dropdown-btn"
                onClick={() => setShowDropdown(!showDropdown)}
              >
                <span className="asset-dot"></span>
                <span className="asset-dropdown-name">
                  {selectedAsset?.name || selectedAssetId}
                </span>
                <ChevronDown size={14} className="dropdown-arrow" />
              </button>

              {showDropdown && (
                <div className="asset-dropdown-menu">
                  {assets.map((asset) => (
                    <button
                      key={asset.id}
                      className={`asset-dropdown-item ${asset.id === selectedAssetId ? 'selected' : ''}`}
                      onClick={() => {
                        onSelectAsset(asset.id);
                        setShowDropdown(false);
                      }}
                    >
                      <div>
                        <div className="asset-item-name">{asset.name}</div>
                        <div className="asset-item-sub">
                          {asset.symbol} • {asset.currency}
                        </div>
                      </div>
                      {asset.id === selectedAssetId && <CheckCircle2 size={14} className="check-icon" />}
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* API Status Badge */}
          <div className="status-pill" title="Backend API Connected">
            <span className="live-dot"></span>
            <span className="status-text">API Online</span>
          </div>

          {/* Financial Disclaimer Modal Trigger */}
          <button
            className="disclaimer-nav-btn"
            onClick={() => setShowModal(true)}
            title="View Financial Risk Disclaimer"
          >
            <ShieldAlert size={16} />
            <span>Disclaimer</span>
          </button>
        </div>
      </div>

      {/* Modal overlay */}
      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal-card" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <div className="modal-icon-badge">
                <ShieldAlert size={22} className="warning-icon" />
              </div>
              <div>
                <h3 className="modal-title">Financial Disclaimer</h3>
                <p className="modal-sub">Important Notice Regarding Predictions</p>
              </div>
            </div>
            <div className="modal-body">
              <p>
                Predictions generated by this application are produced by machine learning algorithms (Linear Regression, SVR, Random Forest, Gradient Boosting) trained on historical market data.
              </p>
              <p>
                <strong>They are statistical estimations for research, technical analysis, and educational demonstration only. They DO NOT constitute financial advice or guaranteed future price targets.</strong>
              </p>
              <p>
                Financial markets carry substantial inherent risk. Always perform independent fundamental research and consult a licensed financial advisor before executing investment decisions.
              </p>
            </div>
            <div className="modal-footer">
              <button className="btn btn-primary btn-full" onClick={() => setShowModal(false)}>
                I Understand & Agree
              </button>
            </div>
          </div>
        </div>
      )}
    </header>
  );
};

export default Navbar;
