import React from 'react';
import { getModelBySlug, MODELS_LIST } from '../data/modelsData';
import ModelHeader from '../components/ModelHeader';
import ModelNavigation from '../components/ModelNavigation';
import PredictionForm from '../components/PredictionForm';
import PredictionResult from '../components/PredictionResult';
import Chart from '../components/Chart';
import AssetSelector from '../components/AssetSelector';
import { Link } from '../router/RouterContext';
import { Sparkles, Layers, AlertCircle, Award, ArrowRight } from 'lucide-react';
import { formatCurrency, formatPercent } from '../utils/formatters';

const ModelPage = ({
  slug,
  assets = [],
  selectedAssetId,
  onSelectAsset,
  predictionData,
  historicalData,
  comparisonData,
  loading,
  error,
  isCustomInput,
  onCustomPrediction,
  onResetRealtime,
}) => {
  const model = getModelBySlug(slug) || MODELS_LIST[0];
  const selectedAsset = assets.find((a) => a.id === selectedAssetId) || assets[0];
  const currency = predictionData?.currency || selectedAsset?.currency || 'USD';

  // Extract other model predictions for quick reference comparison
  const otherPredictions = predictionData?.predictions
    ? Object.keys(predictionData.predictions)
        .filter((k) => k !== model.key)
        .slice(0, 3)
        .map((k) => predictionData.predictions[k])
    : [];

  return (
    <div className="single-model-page">
      {/* Model Navigation Bar */}
      <ModelNavigation modelSlug={model.slug} activeTab="prediction" />

      {/* Model Header */}
      <ModelHeader model={model} assetName={selectedAsset?.name} />

      {/* Target Asset Selector Bar */}
      {assets.length > 0 && (
        <div className="model-page-asset-bar">
          <div className="asset-bar-header">
            <span className="sub-badge">Target Financial Asset</span>
            <h3 className="asset-bar-title">Select Asset for Prediction</h3>
            <p className="asset-bar-desc">
              Choose a market asset to evaluate real-time model predictions and historical performance.
            </p>
          </div>
          <AssetSelector
            assets={assets}
            selectedAssetId={selectedAssetId}
            onSelectAsset={onSelectAsset}
          />
        </div>
      )}

      {/* Connection Error Banner */}
      {error && (
        <div className="error-banner-card">
          <AlertCircle size={20} className="error-icon" />
          <div>
            <h4>Backend Communication Warning</h4>
            <p>{error}</p>
          </div>
        </div>
      )}

      {/* Grid: Form & Result */}
      <div className="model-prediction-grid">
        <div className="grid-left-form">
          <PredictionForm
            model={model}
            marketData={predictionData?.market_data}
            currency={currency}
            isCustomInput={isCustomInput}
            onSubmitCustom={onCustomPrediction}
            onResetRealtime={onResetRealtime}
            loading={loading}
          />
        </div>

        <div className="grid-right-result">
          <PredictionResult
            modelKey={model.key}
            modelName={model.name}
            predictionData={predictionData}
            currency={currency}
            loading={loading}
            error={error}
          />
        </div>
      </div>

      {/* Quick Comparison Row with Other Models */}
      {predictionData && predictionData.predictions && (
        <section className="model-page-section">
          <div className="section-title-header">
            <Layers className="section-title-icon" size={20} />
            <div>
              <h3>How {model.name} Compares on {selectedAsset?.name}</h3>
              <p className="section-subtext">
                Simultaneous predictions generated by alternative regression models for the same session input:
              </p>
            </div>
          </div>

          <div className="other-predictions-grid">
            {otherPredictions.map((other) => {
              const otherModelObj = MODELS_LIST.find((m) => m.key === other.model_key);
              const isBest = predictionData.recommended_best_model === other.model_key;

              return (
                <div key={other.model_key} className="other-pred-card">
                  <div className="other-card-top">
                    <span className="other-name">{other.model_name}</span>
                    {isBest && (
                      <span className="best-ribbon font-badge">
                        <Award size={11} /> Best Model
                      </span>
                    )}
                  </div>
                  <div className="other-price">
                    {formatCurrency(other.predicted_close, currency)}
                  </div>
                  <div className="other-diff">
                    Diff vs Open: {other.diff_from_open > 0 ? '+' : ''}
                    {formatCurrency(other.diff_from_open, currency)} ({formatPercent(other.percentage_diff)})
                  </div>
                  {otherModelObj && (
                    <Link to={`/models/${otherModelObj.slug}`} className="other-link">
                      Switch to {otherModelObj.name} <ArrowRight size={12} />
                    </Link>
                  )}
                </div>
              );
            })}
          </div>
        </section>
      )}

      {/* Charts Section */}
      <section className="model-page-section">
        <Chart
          historicalData={historicalData}
          metadata={predictionData}
          comparisonData={comparisonData}
          currency={currency}
          assetName={selectedAsset?.name}
          selectedModelKey={model.key}
        />
      </section>

      {/* Link to About Model Educational Page */}
      <div className="educational-banner-card">
        <div>
          <h3>Want to learn the mathematical mechanics of {model.name}?</h3>
          <p>
            Read our step-by-step breakdown of feature inputs, mathematical equations, training pipeline, and limitations.
          </p>
        </div>
        <Link to={`/models/${model.slug}/about`} className="btn btn-primary">
          <Sparkles size={16} /> Read About {model.name}
        </Link>
      </div>
    </div>
  );
};

export default ModelPage;
